filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /src/logs/
    json:
      keys_under_root: true
      add_error_key: true

output.logstash:
  enabled: true
  hosts: [ "logstash:5045" ]