GNU nano 6.2                                                                                 docker-compose-api_2.yml
version: "3"

services:

  api:
    build:
      context: ./src_2
    env_file:
      - src_2/.env
    container_name: api
    expose:
      - "80"
    volumes:
      - ./src_2/:/var/www/ugc_api
    restart: always

  filebeat:
    build:
      context: ./filebeat
    container_name: filebeat
    volumes:
      - ./src_2/logs/:/src/logs/
      - ./tmp/logs/nginx/:/var/log/nginx/
    depends_on:
      - api

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./data/models:/var/www/html/models
      - ./tmp/logs/nginx/:/var/log/nginx
    depends_on:
      - api
