version: "3.9"

services:
  nginx-proxi-pass:
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/nginx/docker_nginx_proxi_pass.conf
    depends_on:
      - users-content-api
    ports:
      - "80:80"

  users-content-api:
    volumes:
      - ./users_content_api/src:/app
    env_file: ./config/users_content_api/.env.users_content_api
    build:
      context: .
      dockerfile: dockerfiles/users_content_api/users_content_api.conf
    depends_on:
      - mongos1
      - cache
    ports:
      - "8001:8001"
    expose:
      - "8001"

  tests:
    volumes:
      - ./tests:/tests
    env_file: ./config/tests/.env.tests
    build:
      context: .
      dockerfile: dockerfiles/docker_tests.conf
    depends_on:
      - pg-auth

  cache:
    image: redis:6.2-alpine
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - cache:/data
    env_file: ./config/redis/.env.redis
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  mongos1:
    container_name: mongos1
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
      - mongors1n1
      - mongors1n2
      - mongors1n3
      - mongors2n1
      - mongors2n2
      - mongors2n3
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - mongodb_cluster_router01_db:/data/db
      - /etc/localtime:/etc/localtime:ro
      - ./config/mongo/scripts:/scripts

  mongos2:
    container_name: mongos2
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
      - mongors1n1
      - mongors1n2
      - mongors1n3
      - mongors2n1
      - mongors2n2
      - mongors2n3
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27017 --bind_ip_all
    ports:
      - 27020:27017
    expose:
      - "27017"
    volumes:
      - mongodb_cluster_router02_db:/data/db
      - /etc/localtime:/etc/localtime:ro
      - ./config/mongo/scripts:/scripts

  mongors1n1:
    container_name: mongors1n1
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data_mongors1n1:/data/db
      - ./config/mongo/scripts:/scripts

  mongors1n2:
    container_name: mongors1n2
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - 27027:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data_mongors1n2:/data/db
      - ./config/mongo/scripts:/scripts

  mongors1n3:
    container_name: mongors1n3
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    ports:
      - 27037:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data_mongors1n3:/data/db
      - ./config/mongo/scripts:/scripts

  mongors2n1:
    container_name: mongors2n1
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
      - 27047:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data_mongors2n1:/data/db
      - ./config/mongo/scripts:/scripts

  mongors2n2:
    container_name: mongors2n2
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
      - 27057:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data_mongors2n2:/data/db
      - ./config/mongo/scripts:/scripts

  mongors2n3:
    container_name: mongors2n3
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    ports:
      - 27067:27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data_mongors2n3:/data/db
      - ./config/mongo/scripts:/scripts

  mongocfg1:
    container_name: mongocfg1
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data_mongocfg1:/data/db
      - data_mongocfg1_config:/data/configdb
      - ./config/mongo/scripts:/scripts

  mongocfg2:
    container_name: mongocfg2
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data_mongocfg2:/data/db
      - data_mongocfg2_config:/data/configdb
      - ./config/mongo/scripts:/scripts

  mongocfg3:
    container_name: mongocfg3
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data_mongocfg3:/data/db
      - data_mongocfg3_config:/data/configdb
      - ./config/mongo/scripts:/scripts

volumes:
  data_mongors1n1:
  data_mongors1n2:
  data_mongors1n3:
  data_mongors2n1:
  data_mongors2n2:
  data_mongors2n3:

  data_mongocfg1:
  data_mongocfg2:
  data_mongocfg3:
  data_mongocfg1_config:
  data_mongocfg2_config:
  data_mongocfg3_config:

  mongodb_cluster_router01_db:
  mongodb_cluster_router01_config:
  mongodb_cluster_router02_db:
  mongodb_cluster_router02_config:

  cache:
