@startuml
skinparam componentStyle uml2
actor Client as client
actor Manager as manager

package "movies service" as movies{
    package "admin_panel" as admin{
        component nginx as admin_nginx
        component admin_panel as admin_panel
        database "movies_db" as movies_db
    }
    package "auth_service" as auth{
        component nginx as auth_nginx
        component "auth_api" as auth_api
        database "auth_db" as auth_db
        database "auth_cache" as auth_cache
    }
    package "search_service" as search{
        component nginx as search_nginx
        component search_api as search_api
        database ElasticSearch
        component etl as search_etl
    }
}


auth_api -- auth_db
auth_api -- auth_cache
admin_panel -- movies_db
search_api -- ElasticSearch

movies_db -> search_etl
search_etl -> ElasticSearch

client <--> search_nginx : User Request
manager <--> admin_nginx : DB Administration
admin_nginx <--> admin_panel
search_nginx <--> search_api
auth_nginx <--> auth_api
client <-> auth_nginx : Authorization
search_api <-> auth_nginx : Authentication
admin_panel <-> auth_nginx : Authentication

@enduml