name: Yandex practicum workflow
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  linter:
    name: Linter check and report
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Installing Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Mkdirs for wemake reports
      run: |
        mkdir -p reports/src/wemake-python-styleguide/
        mkdir -p reports/etl/wemake-python-styleguide/
    - name: Pip install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install wemake-python-styleguide
        pip install flake8-html
        pip install mypy
        pip install lxml
        pip install types-protobuf
    - name: flake8 and wemake check
      run: |
          flake8 ./src/ --exit-zero --format=html --htmldir=reports/src/wemake-python-styleguide/
          flake8 ./etl/ --exit-zero --format=html --htmldir=reports/etl/wemake-python-styleguide/
    - name: mypy check
      run: |
          mypy --html-report reports/src/mypy/ src/* || true
          mypy --html-report reports/etl/mypy/ etl/* || true
    - name: Upload reports
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: reports/

  send_message:
    name: Senf to telegram
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: send a message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message:  ${{ github.actor }} touch dev branch in repo ${{ github.repository }}
