version: "3.9"

services:

  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    hostname: zookeeper

  clickhouse-node1-benchmark:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-node1-benchmark
    hostname: clickhouse-node1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./config/clickhouse/init/node1_shard.sql:/docker-entrypoint-initdb.d/node1_shard.sql
      - ./config/clickhouse/data/node1:/etc/clickhouse-server
      - clickhouse_data01b:/var/lib/clickhouse
    depends_on:
      - zookeeper

  clickhouse-node2-benchmark:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-node2-benchmark
    hostname: clickhouse-node2
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ./config/clickhouse/init/node2_replica.sql:/docker-entrypoint-initdb.d/node2_replica.sql
      - ./config/clickhouse/data/node2:/etc/clickhouse-server
      - clickhouse_data02b:/var/lib/clickhouse
    depends_on:
      - zookeeper

  clickhouse-node3-benchmark:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-node3-benchmark
    hostname: clickhouse-node3
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - ./config/clickhouse/init/node3_shard.sql:/docker-entrypoint-initdb.d/node3_shard.sql
      - ./config/clickhouse/data/node3:/etc/clickhouse-server
      - clickhouse_data03b:/var/lib/clickhouse
    depends_on:
      - zookeeper

  clickhouse-node4-benchmark:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-node4-benchmark
    hostname: clickhouse-node4
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - ./config/clickhouse/init/node4_replica.sql:/docker-entrypoint-initdb.d/node4_replica.sql
      - ./config/clickhouse/data/node4:/etc/clickhouse-server
      - clickhouse_data04b:/var/lib/clickhouse
    depends_on:
      - zookeeper

  vertica-benchmark:
    image: jbfavre/vertica
    hostname: vertica_benchmark
    volumes:
      - ./config/vertica/vertica_init.sql:/docker-entrypoint-initdb.d/vertica_init.sql
      - vertica_data_b:/home/dbadmin/docker
    ports:
      - 5433:5433

volumes:
  clickhouse_data01b:
  clickhouse_data02b:
  clickhouse_data03b:
  clickhouse_data04b:
  vertica_data_b:
